### ISSUE TITLE
github&git勉強会

### ISSUE THREAD

**Issue by circled9** [CodeForNiigata/studies#1]
githubも使い始めたので、近いうちにgithubとgitの勉強会をしたいと思います。

いきなりgitだとハードルが高いので、以下のような構成がいいかなと思います。
- 第1回
  - gitの基本その1
    - 概念的なところを中心に
    - 具体的なコマンドに踏み込まない程度に
  - githubを使ってみよう
- 第2回
  - gitの考え方その2
    - pushとかpullとか
  - gitを使ってみよう
    - 超基本的なところを
  - SourceTreeを使ってみよう

**Comment by Nkzn** [comment]
:+1: 
いいですね :laughing: 

ここ３年くらいでGitHubに上げたデータがほとんど日本語テキストという立場でGitHubの話をしてみたい感じもします。

**Comment by circled9** [comment]
やる予定がないのでcloseします。

やることになったらまたIssue立てましょう。
